{
 "title": "Z21",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Main track electricity ",
   "type": "timeseries",
   "description": "Strom am Hauptgleis in Ampere (A)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "z21Exporter_systemstate_maincurrent{job=\"z21_exporter\"}",
     "legendFormat": "Z21"
    }
   ]
  },
  {
   "title": "Filtered main track current ",
   "type": "timeseries",
   "description": "Geglätteter Strom am Hauptgleis in Ampere (A)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "z21Exporter_systemstate_filteredmaincurrent{job=\"z21_exporter\"}",
     "legendFormat": "Z21"
    }
   ]
  },
  {
   "title": "Programming track current",
   "type": "timeseries",
   "description": "Strom am Programmiergleis in Ampere (A)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "z21Exporter_systemstate_progcurrent{job=\"z21_exporter\"}",
     "legendFormat": "Z21"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "z21Exporter_systemstate_temperature{job=\"z21_exporter\"}",
     "legendFormat": "Z21"
    }
   ]
  },
  {
   "title": "Supply Voltage",
   "type": "timeseries",
   "description": "Versorgungsspannung in Volt (V)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "z21Exporter_systemstate_supplyvoltage{job=\"z21_exporter\"}",
     "legendFormat": "Z21"
    }
   ]
  },
  {
   "title": "VCC Voltage",
   "type": "timeseries",
   "description": "interne Spannung, identisch mit Gleisspannung in Volt (V)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "z21Exporter_systemstate_vccvoltage{job=\"z21_exporter\"}",
     "legendFormat": "Z21"
    }
   ]
  }
 ]
}